/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalManagementViews;

import InternalDialogs.BrandsOpsIFGUI;
import InternalDialogs.JobsOpsIFGUI;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Cargos;
import model.bean.Marcas;
import model.dao.CargosDAO;
import model.dao.MarcasDAO;

/**
 *
 * @author focuswts
 */
public class JobsMgmtIFGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form BrandsMgmtIFGUI
     */
    public JobsMgmtIFGUI() {
        initComponents();
        fill_tbJobs();
    }

    private void fill_tbJobs() {

        DefaultTableModel aModel = (DefaultTableModel) tb_Jobs.getModel();
        try {
            CargosDAO cDAO = new CargosDAO();
            ArrayList<Cargos> Cargos = null;
            Cargos = cDAO.findAll();

            int numLinhas = aModel.getRowCount();
            for (int i = 0; i < numLinhas; i++) {
                aModel.removeRow(0);
            }
            for (int i = 0; i < Cargos.size(); i++) {
                Object[] rowDados = new Object[1];
                rowDados[0] = Cargos.get(i).getFuncao();
                aModel.addRow(rowDados);
            }
            this.tb_Jobs.setModel(aModel);
        } catch (Exception e) {
            System.out.println("Erro Ao Preencher JTable: " + e);
        }

    }

    private Cargos fieldsToOBJ() {
        Cargos c = new Cargos();
        CargosDAO cDAO = new CargosDAO();
        try {
            String funcao = tb_Jobs.getValueAt(tb_Jobs.getSelectedRow(), 0).toString();
            int idCargo = cDAO.getIdCargos(funcao);
            c.setId(idCargo);
            c.setFuncao(funcao);
            return c;
        } catch (Exception e) {
            System.out.println("Erro AO Gerar OBJ: " + e);
            return null;
        }

    }

    private void deleteJob() {
        Cargos c = new Cargos();
        CargosDAO cDAO;
        cDAO = new CargosDAO();
        int idCargo = cDAO.getIdCargos(tb_Jobs.getValueAt(tb_Jobs.getSelectedRow(), 0).toString());
        try {
            c.setId(idCargo);
            if (cDAO.delete(c) == true) {
                JOptionPane.showMessageDialog(this, "Cargo Excluído Com Sucesso!");
            }
            fill_tbJobs();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Deletar Cargo: " + e);
        }

    }

    private void viewOpsJobs(String operacao) {
        JobsOpsIFGUI viewJobs;
        try {
            if (operacao.equals("Add")) {
                viewJobs = new JobsOpsIFGUI(null, true, operacao);
                this.getParent().add(viewJobs);
                viewJobs.toFront();
                viewJobs.setVisible(true);
            }
            if (operacao.equals("Edit")) {
                viewJobs = new JobsOpsIFGUI(null, true, operacao, fieldsToOBJ());
                this.getParent().add(viewJobs);
                viewJobs.toFront();
                viewJobs.setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Abrir View Ops Jobs: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Jobs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_Add = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();

        setClosable(true);
        setTitle("Menu Cargos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Lista De Cargos");

        tb_Jobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Função"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Jobs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_Jobs);

        btn_Add.setText("Adicionar Cargo");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Edit.setText("Editar Cargo");
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Delete.setText("Excluir Cargo");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Add)
                .addGap(18, 18, 18)
                .addComponent(btn_Edit)
                .addGap(18, 18, 18)
                .addComponent(btn_Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Add)
                    .addComponent(btn_Edit)
                    .addComponent(btn_Delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        String operacao = "Add";
        viewOpsJobs(operacao);
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        if (!tb_Jobs.getSelectionModel().isSelectionEmpty()) {
            String operacao = "Edit";
            viewOpsJobs(operacao);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione Uma Linha!");
        }

    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        if (!tb_Jobs.getSelectionModel().isSelectionEmpty()) {
            deleteJob();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione Uma Linha!");
        }

    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        fill_tbJobs();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Jobs;
    // End of variables declaration//GEN-END:variables
}
