/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalManagementViews;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Clientes;
import model.bean.FormasEntrega;
import model.bean.Pacotes;
import model.dao.ClientesDAO;
import model.dao.FormasEntregaDAO;
import model.dao.PacotesDAO;

/**
 *
 * @author focuswts
 */
public class PackageMgmtIFGUI extends javax.swing.JInternalFrame {

    private static String tipoBotao;

    public static String getTipoBotao() {
        return tipoBotao;
    }

    public static void setTipoBotao(String aTipoBotao) {
        tipoBotao = aTipoBotao;
    }

    /**
     * Creates new form PackageMgmtIFGUI
     */
    public PackageMgmtIFGUI() {
        initComponents();
        fill_tbPackages("Ativo");
        this.tipoBotao = "Inativo";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Packages = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_Del = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();
        btn_View = new javax.swing.JButton();
        btn_Delivery = new javax.swing.JButton();
        btn_oldPackages = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerenciamento De Pacotes");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tb_Packages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Forma Entrega", "Código Rastreio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Packages.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tb_Packages);

        jLabel1.setFont(new java.awt.Font("Khmer OS System", 1, 14)); // NOI18N
        jLabel1.setText("Lista De Pacotes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Del.setText("Excluir Pacote");
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        btn_Add.setText("Adicionar Pacote");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_View.setText("Ver Dados");
        btn_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewActionPerformed(evt);
            }
        });

        btn_Delivery.setText("Enviar Pacote Para Entrega");
        btn_Delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeliveryActionPerformed(evt);
            }
        });

        btn_oldPackages.setText("Ver Pacotes Antigos");
        btn_oldPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oldPackagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_View)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Del)
                .addGap(18, 18, 18)
                .addComponent(btn_Delivery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btn_oldPackages))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_View)
                    .addComponent(btn_Add)
                    .addComponent(btn_Del)
                    .addComponent(btn_Delivery)
                    .addComponent(btn_oldPackages))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        if (!tb_Packages.getSelectionModel().isSelectionEmpty()) {
            deletePackage();
            fill_tbPackages("Ativo");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione Uma Linha!");
        }
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        String operacao = "Add";
        try {
            PackageInfoIFGUI viewInfo = new PackageInfoIFGUI(operacao);
            this.getParent().add(viewInfo);
            viewInfo.toFront();
            viewInfo.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }

    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewActionPerformed
        if (!tb_Packages.getSelectionModel().isSelectionEmpty()) {
            String operacao = "View";
            PackageInfoIFGUI viewInfo = new PackageInfoIFGUI(fieldToObj(), operacao);
            this.getParent().add(viewInfo);

            viewInfo.toFront();
            viewInfo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione Uma Linha!");
        }
    }//GEN-LAST:event_btn_ViewActionPerformed

    private void btn_DeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeliveryActionPerformed
        if (!tb_Packages.getSelectionModel().isSelectionEmpty()) {
            String operacao = "ViewDelivery";
            PackageInfoIFGUI viewInfo = new PackageInfoIFGUI(fieldToObj(), operacao);
            this.getParent().add(viewInfo);

            viewInfo.toFront();
            viewInfo.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione Uma Linha!");
        }
    }//GEN-LAST:event_btn_DeliveryActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        fill_tbPackages("Ativo");
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        fill_tbPackages("Ativo");
    }//GEN-LAST:event_formInternalFrameActivated

    private void btn_oldPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oldPackagesActionPerformed
        try {
            if (tipoBotao.equals("Ativo")) {
                btn_Delivery.setVisible(true);
                changePackageMode("Ativo");
                this.tipoBotao = "Inativo";
            } else {
                btn_Delivery.setVisible(false);
                changePackageMode("Inativo");
                this.tipoBotao = "Ativo";
            }

        } catch (Exception e) {
            System.out.println("Erro Ao Adaptar Pacotes Antigos");
        }


    }//GEN-LAST:event_btn_oldPackagesActionPerformed

    private void changePackageMode(String tipoBotao) {
        try {
            if (tipoBotao.equals("Ativo")) {
                btn_oldPackages.setText("Ver Pacotes Inativos");
                fill_tbPackages(tipoBotao);
            } else {
                btn_oldPackages.setText("Ver Pacotes Ativos");
                fill_tbPackages(tipoBotao);
            }
            tipoBotao = "Inativo";
        } catch (Exception e) {
            System.out.println("Erro Ao Preencher Lista Com Pacotes Antigos: " + e);
        }

    }

    private void fill_tbPackages(String status) {

        DefaultTableModel aModel = (DefaultTableModel) tb_Packages.getModel();
        try {
            PacotesDAO pDAO = new PacotesDAO();
            ArrayList<Pacotes> Pacotes = null;
            Pacotes = pDAO.findAllStatus(status);

            int numLinhas = aModel.getRowCount();

            for (int i = 0; i < numLinhas; i++) {
                aModel.removeRow(0);
            }

            for (int i = 0; i < Pacotes.size(); i++) {
                Object[] rowDados = new Object[4];
                rowDados[0] = Pacotes.get(i).getIdCliente().getNome();
                rowDados[1] = Pacotes.get(i).getIdForma().getForma();
                rowDados[2] = Pacotes.get(i).getCodigoRastreio();
                aModel.addRow(rowDados);

            }

            this.tb_Packages.setModel(aModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Preencher TB Packages! " + e);
        }

    }

    private void deletePackage() {
        PacotesDAO pDAO = new PacotesDAO();
        try {
            Pacotes p = fieldToObj();
            p.setStatus("Inativo");
            pDAO.disable(p);
            JOptionPane.showMessageDialog(this, "Pacote Excluido Com Sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Excluir Pacote: " + e);
        }

    }

    private void setRestOfDataToObjs(Clientes c, FormasEntrega dw) {
        FormasEntregaDAO dwDAO = new FormasEntregaDAO();
        ClientesDAO cDAO = new ClientesDAO();
        ArrayList<FormasEntrega> ListaFormasEntrega;
        ArrayList<Clientes> ListaClientes;
        try {
            String nomeCliente = tb_Packages.getValueAt(tb_Packages.getSelectedRow(), 1).toString();
            ListaFormasEntrega = dwDAO.findAllWhere(dw); //Pega Dados Do BD Através Do Nome Da Forma
            ListaClientes = cDAO.findAllWhere(nomeCliente);

            for (int i = 0; i < ListaFormasEntrega.size(); i++) {
                int id = ListaFormasEntrega.get(i).getId();
                dw.setId(id); //Atribui O Id Que Faltava No Objeto
            }
            for (int i = 0; i < ListaClientes.size(); i++) {
                int id = ListaClientes.get(i).getId();
                c.setId(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Inserir O Resto Das Informações! : " + e);
        }

    }

    private Pacotes fieldToObj() {
        Pacotes p = new Pacotes();
        PacotesDAO pDAO = new PacotesDAO();
        FormasEntrega dw = new FormasEntrega();
        Clientes c = new Clientes();
        try {
            String codigoRastreio = tb_Packages.getValueAt(tb_Packages.getSelectedRow(), 2).toString();
            int idPacote = pDAO.findIdPackage(codigoRastreio);

            p.setId(idPacote);
            p.setCodigoRastreio(codigoRastreio);
            dw.setForma(tb_Packages.getValueAt(tb_Packages.getSelectedRow(), 1).toString());
            setRestOfDataToObjs(c, dw);
            p.setIdForma(dw);
            return p;
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Erro Ao Criar Obj Pacote!: " + e);
            return null;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Delivery;
    private javax.swing.JButton btn_View;
    private javax.swing.JButton btn_oldPackages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tb_Packages;
    // End of variables declaration//GEN-END:variables
}
