/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExternalViews;

import InternalDialogs.VehiclesOpsMenuIFGUI;
import InternalManagementViews.ClientsMgmtIFGUI;
import InternalManagementViews.DeliveriesMgmtIFGUI;
import InternalManagementViews.DeliveryWaysMgmtIFGUI;
import InternalManagementViews.PackageMgmtIFGUI;
import InternalManagementViews.UsersMgmtIFGUI;
import InternalManagementViews.WorkersMgmtIFGUI;
import InternalViews.Menu.MenuOperationsGUI;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import model.bean.Usuarios;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author focuswts
 */
public class menuGUI extends javax.swing.JFrame {

    /**
     * Creates new form menuGUI
     */
    private static Usuarios user;
    private static Connection con;
    
    public menuGUI() {
        initComponents();
        menuView();
    }
    
    public menuGUI(Usuarios u) {
        initComponents();
        this.user = u;
        menuView();
    }
    
    public menuGUI(Usuarios u, Connection con) {
        initComponents();
        this.user = u;
        this.con = con;
        menuView();
    }
    
    public void logout() {
        try {
            this.dispose();
        } catch (Exception e) {
            System.out.println("Erro Ao Fazer Logout: " + e);
        }
        
    }
    
    public static void loginView() {
        try {
            loginGUI viewLogin = new loginGUI();
            viewLogin.setVisible(true);
        } catch (Exception e) {
        }
    }
    
    private void menuView() {
        try {
            MenuOperationsGUI viewMenu = new MenuOperationsGUI(this.user, this);
            dp_DesktopMenu.add(viewMenu);
            Dimension d = this.dp_DesktopMenu.getSize();
            viewMenu.setSize(d);
            viewMenu.setMaximum(true);
            viewMenu.setClosable(false);
            viewMenu.setResizable(false);
            viewMenu.setVisible(true);
            teste();
        } catch (Exception e) {
        }
        
    }
    
    private void teste() {
        System.out.println("User: " + user.getLogin());
        System.out.println("Permission: " + user.getNivel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp_DesktopMenu = new modelsUtil.JDesktopPaneBackground("/images/BGTCargoSystemMenuBackground.png");
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_Packages = new javax.swing.JMenuItem();
        mi_Workers = new javax.swing.JMenuItem();
        mi_Clients = new javax.swing.JMenuItem();
        mi_Vehicles = new javax.swing.JMenuItem();
        mi_DeliveryWays = new javax.swing.JMenuItem();
        mi_Deliveries = new javax.swing.JMenuItem();
        mi_Users = new javax.swing.JMenuItem();
        mi_Branchs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_Veiculos = new javax.swing.JMenuItem();
        mi_Clientes = new javax.swing.JMenuItem();
        mi_Funcionarios = new javax.swing.JMenuItem();
        mi_Pacotes = new javax.swing.JMenuItem();
        mi_Entregas = new javax.swing.JMenuItem();
        mi_Usuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BGTCargoSystem Menu");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenu1.setText("Operações");

        mi_Packages.setText("Pacotes");
        mi_Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_PackagesActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Packages);

        mi_Workers.setText("Funcionários");
        mi_Workers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_WorkersActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Workers);

        mi_Clients.setText("Clientes");
        mi_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ClientsActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Clients);

        mi_Vehicles.setText("Veículos");
        mi_Vehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_VehiclesActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Vehicles);

        mi_DeliveryWays.setText("Formas De Entrega");
        mi_DeliveryWays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_DeliveryWaysActionPerformed(evt);
            }
        });
        jMenu1.add(mi_DeliveryWays);

        mi_Deliveries.setText("Entregas");
        mi_Deliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_DeliveriesActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Deliveries);

        mi_Users.setText("Usuários");
        mi_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_UsersActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Users);

        mi_Branchs.setText("Filiais");
        mi_Branchs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_BranchsActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Branchs);

        menuBar.add(jMenu1);

        jMenu2.setText("Relatórios");

        mi_Veiculos.setText("Veículos");
        mi_Veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_VeiculosActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Veiculos);

        mi_Clientes.setText("Clientes");
        mi_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Clientes);

        mi_Funcionarios.setText("Funcionários");
        mi_Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_FuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Funcionarios);

        mi_Pacotes.setText("Pacotes");
        mi_Pacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_PacotesActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Pacotes);

        mi_Entregas.setText("Entregas");
        mi_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_EntregasActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Entregas);

        mi_Usuarios.setText("Usuários");
        mi_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_UsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mi_Usuarios);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_DesktopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp_DesktopMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_DeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_DeliveriesActionPerformed
        DeliveriesMgmtIFGUI viewDeliveries = new DeliveriesMgmtIFGUI();
        addToDesktop(viewDeliveries);
    }//GEN-LAST:event_mi_DeliveriesActionPerformed

    private void mi_PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_PackagesActionPerformed
        PackageMgmtIFGUI viewPackages = new PackageMgmtIFGUI();
        dp_DesktopMenu.add(viewPackages);
        try {
            viewPackages.setMaximum(true);
            viewPackages.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_PackagesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        viewLogin();
    }//GEN-LAST:event_formWindowClosed

    private void mi_WorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_WorkersActionPerformed
        WorkersMgmtIFGUI viewWorkers = new WorkersMgmtIFGUI();
        addToDesktop(viewWorkers);

    }//GEN-LAST:event_mi_WorkersActionPerformed

    private void mi_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ClientsActionPerformed
        ClientsMgmtIFGUI viewClients = new ClientsMgmtIFGUI();
        addToDesktop(viewClients);
    }//GEN-LAST:event_mi_ClientsActionPerformed

    private void mi_VehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_VehiclesActionPerformed
        VehiclesOpsMenuIFGUI viewVehiclesMenu = new VehiclesOpsMenuIFGUI();
        addToDesktop(viewVehiclesMenu);
    }//GEN-LAST:event_mi_VehiclesActionPerformed

    private void mi_DeliveryWaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_DeliveryWaysActionPerformed
        DeliveryWaysMgmtIFGUI viewDeliveryWays = new DeliveryWaysMgmtIFGUI();
        addToDesktop(viewDeliveryWays);
    }//GEN-LAST:event_mi_DeliveryWaysActionPerformed

    private void mi_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_UsersActionPerformed
        UsersMgmtIFGUI viewUsers = new UsersMgmtIFGUI();
        addToDesktop(viewUsers);
    }//GEN-LAST:event_mi_UsersActionPerformed

    private void mi_BranchsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_BranchsActionPerformed
    }//GEN-LAST:event_mi_BranchsActionPerformed

    private void mi_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ClientesActionPerformed
        String srcDir = "RelatorioClientes.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_ClientesActionPerformed

    private void mi_FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_FuncionariosActionPerformed
        String srcDir = "RelatorioFuncionarios.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_FuncionariosActionPerformed

    private void mi_VeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_VeiculosActionPerformed
        String srcDir = "RelatorioVeiculos.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_VeiculosActionPerformed

    private void mi_PacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_PacotesActionPerformed
        String srcDir = "RelatorioPacotes.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_PacotesActionPerformed

    private void mi_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_EntregasActionPerformed
        String srcDir = "RelatorioEntregas.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_EntregasActionPerformed

    private void mi_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_UsuariosActionPerformed
        String srcDir = "RelatorioUsuarios.jasper";
        gerarRelatorio(srcDir);
    }//GEN-LAST:event_mi_UsuariosActionPerformed
    
    private void gerarRelatorio(String srcDir) {
        String src = srcDir;
        
        JasperPrint jasperPrint = null;
        
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, con);
        } catch (JRException ex) {
            System.out.println(ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        
        view.setVisible(true);
        
    }
    
    public static void adaptMenuItems() {
        try {
            mi_DeliveryWays.setVisible(false);
            mi_Users.setVisible(false);
            mi_Vehicles.setVisible(false);
            mi_Branchs.setVisible(false);
        } catch (Exception e) {
            System.out.println("Erro Ao Adaptar Itens Menu: " + e);
        }
    }
    
    private void addToDesktop(JInternalFrame view) {
        dp_DesktopMenu.add(view);
        try {
            view.setMaximum(true);
            view.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(menuGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void viewLogin() {
        try {
            loginGUI viewLogin = new loginGUI();
            viewLogin.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro AO Abrir Tela Login: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static modelsUtil.JDesktopPaneBackground dp_DesktopMenu;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public static javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenuItem mi_Branchs;
    private javax.swing.JMenuItem mi_Clientes;
    public static javax.swing.JMenuItem mi_Clients;
    public static javax.swing.JMenuItem mi_Deliveries;
    public static javax.swing.JMenuItem mi_DeliveryWays;
    private javax.swing.JMenuItem mi_Entregas;
    private javax.swing.JMenuItem mi_Funcionarios;
    public static javax.swing.JMenuItem mi_Packages;
    private javax.swing.JMenuItem mi_Pacotes;
    public static javax.swing.JMenuItem mi_Users;
    private javax.swing.JMenuItem mi_Usuarios;
    public static javax.swing.JMenuItem mi_Vehicles;
    private javax.swing.JMenuItem mi_Veiculos;
    public static javax.swing.JMenuItem mi_Workers;
    // End of variables declaration//GEN-END:variables

    public Usuarios getUser() {
        return user;
    }
    
    public void setUser(Usuarios user) {
        this.user = user;
    }
    
    public static Connection getCon() {
        return con;
    }
    
    public static void setCon(Connection aCon) {
        con = aCon;
    }
    
}
