/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalViews.Menu;

import ExternalViews.menuGUI;
import InternalDialogs.VehiclesOpsMenuIFGUI;
import InternalManagementViews.ClientsMgmtIFGUI;
import InternalManagementViews.DeliveriesMgmtIFGUI;
import InternalManagementViews.DeliverySituationsMgmtIFGUI;
import InternalManagementViews.DeliveryWaysMgmtIFGUI;
import InternalManagementViews.JobsMgmtIFGUI;
import InternalManagementViews.PackageMgmtIFGUI;
import InternalManagementViews.RoutesMgmtIFGUI;
import InternalManagementViews.UsersMgmtIFGUI;
import InternalManagementViews.WorkersMgmtIFGUI;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.bean.Usuarios;

/**
 *
 * @author focuswts
 */
public class MenuOperationsGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuOperationsGUI
     */
    public static Usuarios user;
    private JFrame frame;

    public MenuOperationsGUI() {
        initComponents();
        removeDropdownLeftTop();
    }

    public MenuOperationsGUI(Usuarios u) {
        initComponents();
        removeDropdownLeftTop();
        this.user = u;
        adaptView();
        adaptMenu();
    }

    public MenuOperationsGUI(Usuarios u, JFrame frame) {
        initComponents();
        removeDropdownLeftTop();
        this.user = u;
        this.frame = frame;
        adaptView();
        adaptMenu();
    }

    private void adaptView() {
        try {
            ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setEastPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setWestPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setSouthPane(null);
            txt_User.setText(user.getLogin());
            txt_Permission.setText(user.getNivel());
//            txt_Branch.setText(branch.getFilial());
        } catch (Exception e) {
            System.out.println("erro: " + e);
        }
    }

    private void adaptMenu() {
        try {
            if (user.getNivel().equals("Default")) {
                //     btn_Branchs.setVisible(false);
                btn_DeliveryWays.setVisible(false);
                btn_Vehicles.setVisible(false);
                btn_Users.setVisible(false);

                menuGUI.adaptMenuItems();
            }

        } catch (Exception e) {
            System.out.println("Erro Ao Adaptar Menu: " + e);
        }
    }

    private void removeDropdownLeftTop() {
        try {
            // Title or north pane of the internal frame:
            Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
            // And remove the button:
            pane.remove(0);
            // make it invisible:
            pane.getComponent(0).setVisible(false);

        } catch (Exception e) {
            System.out.println("Erro Ao Remover Dropdown JInternalFrame: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWithBackground1 = new modelsUtil.JPanelWithBackground("/images/backgroundTexture.jpeg");
        jLabel1 = new javax.swing.JLabel();
        btn_Packages = new javax.swing.JButton();
        btn_Workers = new javax.swing.JButton();
        btn_Clients = new javax.swing.JButton();
        btn_Vehicles = new javax.swing.JButton();
        btn_Deliveries = new javax.swing.JButton();
        btn_DeliveryWays = new javax.swing.JButton();
        btn_Users = new javax.swing.JButton();
        btn_Routes = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Permission = new javax.swing.JTextField();
        btn_DeliverySituations = new javax.swing.JButton();
        btn_Jobs = new javax.swing.JButton();

        setBorder(null);
        setTitle("Menu De Operações");

        jLabel1.setFont(new java.awt.Font("Tibetan Machine Uni", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu De Operações");

        btn_Packages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64x64.png"))); // NOI18N
        btn_Packages.setToolTipText("Menu Pacotes");
        btn_Packages.setBorderPainted(false);
        btn_Packages.setContentAreaFilled(false);
        btn_Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PackagesActionPerformed(evt);
            }
        });

        btn_Workers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/worker-brown-icon.png"))); // NOI18N
        btn_Workers.setToolTipText("Menu Funcionários");
        btn_Workers.setBorderPainted(false);
        btn_Workers.setContentAreaFilled(false);
        btn_Workers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WorkersActionPerformed(evt);
            }
        });

        btn_Clients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Office-Client-Male-Light-icon.png"))); // NOI18N
        btn_Clients.setToolTipText("Menu Clientes");
        btn_Clients.setBorderPainted(false);
        btn_Clients.setContentAreaFilled(false);
        btn_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientsActionPerformed(evt);
            }
        });

        btn_Vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/42554-delivery-truck-icon.png"))); // NOI18N
        btn_Vehicles.setToolTipText("Menu Veículos");
        btn_Vehicles.setBorderPainted(false);
        btn_Vehicles.setContentAreaFilled(false);
        btn_Vehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VehiclesActionPerformed(evt);
            }
        });

        btn_Deliveries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/truck-brown-icon.png"))); // NOI18N
        btn_Deliveries.setToolTipText("Menu Entregas");
        btn_Deliveries.setBorderPainted(false);
        btn_Deliveries.setContentAreaFilled(false);
        btn_Deliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeliveriesActionPerformed(evt);
            }
        });

        btn_DeliveryWays.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ecommerce-Delivery-icon.png"))); // NOI18N
        btn_DeliveryWays.setToolTipText("Menu Formas De Entrega");
        btn_DeliveryWays.setBorderPainted(false);
        btn_DeliveryWays.setContentAreaFilled(false);
        btn_DeliveryWays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeliveryWaysActionPerformed(evt);
            }
        });

        btn_Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-male-icon.png"))); // NOI18N
        btn_Users.setToolTipText("Menu De Usuários");
        btn_Users.setBorderPainted(false);
        btn_Users.setContentAreaFilled(false);
        btn_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsersActionPerformed(evt);
            }
        });

        btn_Routes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-waypoint-map-64.png"))); // NOI18N
        btn_Routes.setToolTipText("Menu De Rotas");
        btn_Routes.setBorderPainted(false);
        btn_Routes.setContentAreaFilled(false);
        btn_Routes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RoutesActionPerformed(evt);
            }
        });

        btn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shutdown-64.png"))); // NOI18N
        btn_Logout.setBorderPainted(false);
        btn_Logout.setContentAreaFilled(false);
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        txt_User.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nível Acesso:");

        txt_Permission.setEditable(false);

        btn_DeliverySituations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons48x/stopWatch.png"))); // NOI18N
        btn_DeliverySituations.setToolTipText("Menu Situacoes De Entrega");
        btn_DeliverySituations.setBorderPainted(false);
        btn_DeliverySituations.setContentAreaFilled(false);
        btn_DeliverySituations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeliverySituationsActionPerformed(evt);
            }
        });

        btn_Jobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons48x/checkList.png"))); // NOI18N
        btn_Jobs.setToolTipText("Menu De Cargos");
        btn_Jobs.setBorderPainted(false);
        btn_Jobs.setContentAreaFilled(false);
        btn_Jobs.setPreferredSize(new java.awt.Dimension(78, 78));
        btn_Jobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JobsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWithBackground1Layout = new javax.swing.GroupLayout(jPanelWithBackground1);
        jPanelWithBackground1.setLayout(jPanelWithBackground1Layout);
        jPanelWithBackground1Layout.setHorizontalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackground1Layout.createSequentialGroup()
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Permission, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel1))
                        .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                            .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                    .addComponent(btn_Packages)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Workers)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Clients)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Vehicles))
                                .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                    .addComponent(btn_DeliveryWays)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Users)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Routes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_DeliverySituations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_Jobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Deliveries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelWithBackground1Layout.setVerticalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Logout)
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Packages)
                    .addComponent(btn_Workers)
                    .addComponent(btn_Clients)
                    .addComponent(btn_Vehicles)
                    .addComponent(btn_Deliveries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_DeliveryWays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Routes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_DeliverySituations, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Jobs, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txt_Permission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PackagesActionPerformed
        try {
            PackageMgmtIFGUI viewPackages = new PackageMgmtIFGUI();
            this.getParent().add(viewPackages);
            viewPackages.setMaximum(true);
            viewPackages.setVisible(true);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_PackagesActionPerformed

    private void btn_WorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WorkersActionPerformed
        try {
            WorkersMgmtIFGUI viewWorkers = new WorkersMgmtIFGUI();
            this.getParent().add(viewWorkers);
            viewWorkers.toFront();
            viewWorkers.setMaximum(true);
            viewWorkers.setVisible(true);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_WorkersActionPerformed

    private void btn_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientsActionPerformed
        try {
            ClientsMgmtIFGUI viewClients = new ClientsMgmtIFGUI();
            this.getParent().add(viewClients);
            viewClients.toFront();
            viewClients.setMaximum(true);
            viewClients.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_ClientsActionPerformed

    private void btn_VehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VehiclesActionPerformed
        try {
            VehiclesOpsMenuIFGUI viewVehiclesMenu = new VehiclesOpsMenuIFGUI();
            this.getParent().add(viewVehiclesMenu);
            viewVehiclesMenu.toFront();
            viewVehiclesMenu.setMaximum(true);
            viewVehiclesMenu.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro Ao Abrir Menu Veículos: " + e);
        }

    }//GEN-LAST:event_btn_VehiclesActionPerformed

    private void btn_DeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeliveriesActionPerformed
        try {
            DeliveriesMgmtIFGUI viewDeliveries = new DeliveriesMgmtIFGUI();
            this.getParent().add(viewDeliveries);
            viewDeliveries.toFront();
            viewDeliveries.setMaximum(true);
            viewDeliveries.setVisible(true);
        } catch (Exception e) {
            System.out.println("Erro Ao Abrir Menu Entregas: " + e);
        }
    }//GEN-LAST:event_btn_DeliveriesActionPerformed

    private void btn_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsersActionPerformed
        try {
            UsersMgmtIFGUI viewUsers = new UsersMgmtIFGUI();
            this.getParent().add(viewUsers);
            viewUsers.toFront();
            viewUsers.setMaximum(true);
            viewUsers.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_UsersActionPerformed

    private void btn_DeliveryWaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeliveryWaysActionPerformed
        try {
            DeliveryWaysMgmtIFGUI viewDeliveryW = new DeliveryWaysMgmtIFGUI();
            this.getParent().add(viewDeliveryW);
            viewDeliveryW.toFront();
            viewDeliveryW.setMaximum(true);
            viewDeliveryW.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_DeliveryWaysActionPerformed

    private void btn_RoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RoutesActionPerformed
        try {
            RoutesMgmtIFGUI viewRoutes = new RoutesMgmtIFGUI();
            this.getParent().add(viewRoutes);
            viewRoutes.toFront();
            viewRoutes.setMaximum(true);
            viewRoutes.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_RoutesActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        frame.dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_DeliverySituationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeliverySituationsActionPerformed

        try {
            DeliverySituationsMgmtIFGUI viewDeliveryS = new DeliverySituationsMgmtIFGUI();
            this.getParent().add(viewDeliveryS);
            viewDeliveryS.toFront();
            viewDeliveryS.setMaximum(true);
            viewDeliveryS.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_DeliverySituationsActionPerformed

    private void btn_JobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JobsActionPerformed
        try {
            JobsMgmtIFGUI viewJobs = new JobsMgmtIFGUI();
            this.getParent().add(viewJobs);
            viewJobs.toFront();
            viewJobs.setMaximum(true);
            viewJobs.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_JobsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clients;
    private javax.swing.JButton btn_Deliveries;
    private javax.swing.JButton btn_DeliverySituations;
    private javax.swing.JButton btn_DeliveryWays;
    private javax.swing.JButton btn_Jobs;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Packages;
    private javax.swing.JButton btn_Routes;
    private javax.swing.JButton btn_Users;
    private javax.swing.JButton btn_Vehicles;
    private javax.swing.JButton btn_Workers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private modelsUtil.JPanelWithBackground jPanelWithBackground1;
    private javax.swing.JTextField txt_Permission;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables

    public Usuarios getUser() {
        return user;
    }

    public void setUser(Usuarios user) {
        this.user = user;
    }

}
