/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalDialogs;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import connection.ConnectionFactory;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.bean.Clientes;
import model.bean.Funcionarios;
import model.dao.ClientesDAO;

/**
 *
 * @author focuswts
 */
public class contatosModalIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form contatosModalIF
     */
    Connection con = null;
    private static Funcionarios worker;
    private static Clientes client;
    private static String objContato;

    public contatosModalIF(java.awt.Frame parent, boolean modal, Funcionarios worker, String objContato) {
        initComponents();
        con = (Connection) ConnectionFactory.getConnection();
        this.worker = worker;
        this.objContato = objContato;
        getDados();
    }

    public contatosModalIF(java.awt.Frame parent, boolean modal, Clientes client, String objContato) {
        initComponents();
        con = (Connection) ConnectionFactory.getConnection();
        this.client = client;
        this.objContato = objContato;
        getDados2();
    }

    private void getDados() {
        String sql = null;

        try {
            sql = "SELECT * FROM Funcionarios WHERE nome = ?";
            //   JOptionPane.showMessageDialog(this, "Worker: " + this.worker.getNome());
            PreparedStatement st = (PreparedStatement) con.prepareStatement(sql);
            st.setString(1, worker.getNome());
            ResultSet rs = st.executeQuery();
            if (rs.next()) {

                txt_Celular.setText(rs.getString("celular"));
                txt_Email.setText(rs.getString("email"));
                txt_Endereco.setText(rs.getString("endereco"));
                txt_Telefone.setText(rs.getString("telefone"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Carregar Contatos Do Funcionário!");
        }

    }

    private void getDados2() {
        lb_Title.setText("Contatos Do Cliente");
        String sql = null;
        sql = "SELECT * FROM Clientes WHERE nome = ?";

        try {
            //   JOptionPane.showMessageDialog(this, "Worker: " + this.worker.getNome());
            PreparedStatement st = (PreparedStatement) con.prepareStatement(sql);
            st.setString(1, client.getNome());
            ResultSet rs = st.executeQuery();
            if (rs.next()) {

                txt_Celular.setText(rs.getString("celular"));
                txt_Email.setText(rs.getString("email"));
                txt_Endereco.setText(rs.getString("endereco"));
                txt_Telefone.setText(rs.getString("telefone"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Carregar Contatos Do Cliente!" + e);
        }

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Endereco = new javax.swing.JTextField();
        txt_Telefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Celular = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Contatos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_Title.setText("Contatos Do Funcionário");

        jLabel4.setText("Endereço");

        txt_Endereco.setEditable(false);
        txt_Endereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_Telefone.setEditable(false);
        txt_Telefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setText("Telefone");

        jLabel6.setText("Celular");

        txt_Celular.setEditable(false);
        txt_Celular.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_Email.setEditable(false);
        txt_Email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Endereco))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(txt_Celular)
                                    .addComponent(txt_Email))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 85, Short.MAX_VALUE)
                        .addComponent(lb_Title)
                        .addGap(118, 118, 118))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public Funcionarios getWorker() {
        return worker;
    }

    public void setWorker(Funcionarios worker) {
        this.worker = worker;
    }

    public void setWorkerNome(String nome) {
        this.worker.setNome(nome);

    }

    public static Clientes getClient() {
        return client;
    }

    public void setClient(Clientes client) {
        this.client = client;
    }

    public static String getObjContato() {
        return objContato;
    }

    public void setObjContato(String aObjContato) {
        objContato = aObjContato;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Endereco;
    private javax.swing.JTextField txt_Telefone;
    // End of variables declaration//GEN-END:variables
}
