/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalDialogs;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.bean.Pacotes;
import model.bean.Rotas;
import model.bean.Veiculos;
import model.bean.Funcionarios;
import model.dao.RotasDAO;

/**
 *
 * @author focuswts
 */
public class RouteChooserIFGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form RouteChooserIFUI
     */
    private static Pacotes pacote;
    private static Rotas route;

    public RouteChooserIFGUI() {
        initComponents();
    }

    public RouteChooserIFGUI(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    public RouteChooserIFGUI(java.awt.Frame parent, boolean modal, Pacotes p) {
        initComponents();
        this.pacote = p;
    }

    private Rotas fillRoute(ArrayList<Rotas> rotas) {
        Rotas r = new Rotas();
        try {
            for (int i = 0; i < rotas.size(); i++) {
                int id = rotas.get(i).getId();
                int idFuncionario = rotas.get(i).getIdFuncionario().getId();
                int idVeiculo = rotas.get(i).getIdVeiculo().getId();
                String remetente = rotas.get(i).getRemetente();
                String destinatario = rotas.get(i).getDestinatario();

                r.setId(id);

                Funcionarios w = new Funcionarios();
                w.setId(idFuncionario);

                r.setIdFuncionario(w);

                Veiculos v = new Veiculos();
                v.setId(idVeiculo);
                r.setIdVeiculo(v);

                r.setRemetente(remetente);
                r.setDestinatario(destinatario);

            }
            this.route = r;
            return r;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Preencher Rota: " + e);
            return null;
        }

    }

    private boolean checkRoute() {
        boolean b = false;
        RotasDAO rDAO = new RotasDAO();
        String remetente = txt_Remetente.getText();
        String destinatario = txt_Destinatario.getText();
        ArrayList<Rotas> rotas = null;
        try {
            rotas = rDAO.findAllWhere(remetente, destinatario);
            if (!rotas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Rota Encontrada Com Sucesso!");
                b = true;
                fillRoute(rotas);
                String operacao = "Add";
                viewDeliveriesOps(operacao, pacote, route, b, rotas);

            } else {
                JOptionPane.showMessageDialog(this, "Nenhuma Rota Disponível!");
                b = false;
                viewRoutesOps();
            }
            return b;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Pegar Rota");
        }

        return b;
    }

    private Rotas fieldsToObj() {
        Rotas r = new Rotas();
        try {
            r.setRemetente(txt_Remetente.getText());
            r.setDestinatario(txt_Destinatario.getText());
            return r;
        } catch (Exception e) {
            System.out.println("Erro Ao Criar OBJ: " + e);
            return null;
        }
    }

    private void viewDeliveriesOps(String op, Pacotes p, Rotas r, boolean routeExist, ArrayList<Rotas> rotas) {
        try {
            String operacao = "Add";
            DeliveriesOpsIFGUI viewDeliveries = new DeliveriesOpsIFGUI(null, true, operacao, p, r, routeExist, rotas);
            this.getParent().add(viewDeliveries);
            viewDeliveries.toFront();
            viewDeliveries.setVisible(true);

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    private void viewRoutesOps() {
        try {
            String operacao = "Add";
            RoutesOpsIFGUI viewRoutes = new RoutesOpsIFGUI(null, true, operacao);
            this.getParent().add(viewRoutes);
            viewRoutes.toFront();
            viewRoutes.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro Ao Abrir Routes OPS: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Remetente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Destinatario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_CheckRoute = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe Os Dados Da Rota"));

        jLabel1.setText("Remetente");

        jLabel2.setText("Destinatário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Remetente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_Destinatario))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_CheckRoute.setText("Verificar Rota");
        btn_CheckRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckRouteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(btn_CheckRoute)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btn_CheckRoute)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CheckRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckRouteActionPerformed
        if (checkRoute() == true) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_CheckRouteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CheckRoute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_Destinatario;
    private javax.swing.JTextField txt_Remetente;
    // End of variables declaration//GEN-END:variables
}
